import { saturationTypes, tintNames, colorTemperatures } from './colorConstants';
import { colorNames, simpleColors, complexColorNames } from './colorNames';
import { saturations, hues, tints } from './colorValues';

export const colorList = {
  // MAGENTA
  [complexColorNames.magentaPink]: {
    name: complexColorNames.magentaPink,
    hueName: colorNames.MAGENTA,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.LIGHT,
    hsl: [hues.MAGENTA, saturations.MAGENTA, tints.LIGHT],
    associations: [simpleColors.SIMPLE_PINK, simpleColors.SIMPLE_PURPLE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.magenta]: {
    name: complexColorNames.magenta,
    hueName: colorNames.MAGENTA,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.MID,
    hsl: [hues.MAGENTA, saturations.MAGENTA, tints.MID],
    associations: [simpleColors.SIMPLE_PINK, simpleColors.SIMPLE_PURPLE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkMagenta]: {
    name: complexColorNames.darkMagenta,
    hueName: colorNames.MAGENTA,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.DARK,
    hsl: [hues.MAGENTA, saturations.MAGENTA, tints.DARKER_DARK],
    associations: [simpleColors.SIMPLE_PINK, simpleColors.SIMPLE_PURPLE],
    simpleOpts: { isSimpleColor: false },
  },
  // DESATURATED MAGENTA
  [complexColorNames.duskyMagentaPink]: {
    name: complexColorNames.duskyMagentaPink,
    hueName: colorNames.MAGENTA,
    colorTemperature: colorTemperatures.WARM,
    saturationType: saturationTypes.DESATURATED,
    tintName: tintNames.LIGHT,
    hsl: [hues.MAGENTA, saturations.DESATURATED_MAGENTA, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_PURPLE, simpleColors.SIMPLE_PINK],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.duskyMagenta]: {
    name: complexColorNames.duskyMagenta,
    hueName: colorNames.MAGENTA,
    colorTemperature: colorTemperatures.WARM,
    saturationType: saturationTypes.DESATURATED,
    tintName: tintNames.MID,
    hsl: [hues.MAGENTA, saturations.DESATURATED_MAGENTA, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_PURPLE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.duskyDarkMagenta]: {
    name: complexColorNames.duskyDarkMagenta,
    hueName: colorNames.MAGENTA,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.DARK,
    hsl: [hues.MAGENTA, saturations.DESATURATED_MAGENTA, tints.DESAT_DARK],
    associations: [simpleColors.SIMPLE_PURPLE],
    simpleOpts: { isSimpleColor: false },
  },
  // PINK
  [complexColorNames.pink]: {
    name: complexColorNames.pink,
    hueName: colorNames.PINK,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.LIGHT,
    associations: [simpleColors.SIMPLE_PINK, simpleColors.SIMPLE_RED],
    hsl: [hues.PINK, saturations.PINK, tints.LIGHT],
    simpleOpts: {
      isSimpleColor: true,
      id: simpleColors.SIMPLE_PINK,
      simpleOrder: 0,
    },
  },
  [complexColorNames.midPink]: {
    name: complexColorNames.midPink,
    hueName: colorNames.PINK,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.MID,
    hsl: [hues.PINK, saturations.PINK, tints.MID],
    associations: [simpleColors.SIMPLE_PINK, simpleColors.SIMPLE_RED],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkPink]: {
    name: complexColorNames.darkPink,
    hueName: colorNames.PINK,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    degree: hues.PINK,
    saturation: saturations.PINK,
    tintName: tintNames.DARK,
    tintValue: tints.DARKER_DARK,
    hsl: [hues.PINK, saturations.PINK, tints.DARKER_DARK],
    associations: [simpleColors.SIMPLE_PINK, simpleColors.SIMPLE_RED],
    simpleOpts: { isSimpleColor: false },
  },
  // DESATURATED PINK
  [complexColorNames.duskyPink]: {
    name: complexColorNames.duskyPink,
    hueName: colorNames.PINK,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.LIGHT,
    hsl: [hues.DESATURATED_PINK, saturations.DESATURATED_PINK, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_PURPLE, simpleColors.SIMPLE_PINK],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.duskyMidPink]: {
    name: complexColorNames.duskyMidPink,
    hueName: colorNames.PINK,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.MID,
    hsl: [hues.DESATURATED_PINK, saturations.DESATURATED_PINK, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_PURPLE, simpleColors.SIMPLE_PINK],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.duskyDarkPink]: {
    name: complexColorNames.duskyDarkPink,
    hueName: colorNames.PINK,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.DARK,
    hsl: [hues.DESATURATED_PINK, saturations.DESATURATED_PINK, tints.DESAT_DARK],
    associations: [simpleColors.SIMPLE_PURPLE, simpleColors.SIMPLE_PINK],
    simpleOpts: { isSimpleColor: false },
  },
  // RED
  [complexColorNames.salmon]: {
    name: complexColorNames.salmon,
    hueName: colorNames.RED,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.LIGHT,
    hsl: [hues.RED, saturations.RED, tints.LIGHT],
    associations: [simpleColors.SIMPLE_RED, simpleColors.SIMPLE_PINK],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.red]: {
    name: complexColorNames.red,
    hueName: colorNames.RED,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.MID,
    hsl: [hues.RED, saturations.RED, tints.MID],
    associations: [simpleColors.SIMPLE_RED],
    simpleOpts: {
      id: simpleColors.SIMPLE_RED,
      isSimpleColor: true,
      simpleOrder: 1,
    },
  },
  [complexColorNames.darkRed]: {
    name: complexColorNames.darkRed,
    hueName: colorNames.RED,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.DARK,
    hsl: [hues.RED, saturations.RED, tints.DARK],
    associations: [simpleColors.SIMPLE_RED],
    simpleOpts: { isSimpleColor: false },
  },
  // RED-BROWN (Desaturated red)
  [complexColorNames.lightRedBrown]: {
    name: complexColorNames.lightRedBrown,
    saturationType: saturationTypes.DESATURATED,
    hueName: colorNames.RED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.LIGHT,
    hsl: [hues.DESATURATED_RED, saturations.DESATURATED_RED, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_BROWN, simpleColors.SIMPLE_PINK, simpleColors.SIMPLE_RED],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.redBrown]: {
    name: complexColorNames.redBrown,
    hueName: colorNames.RED,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.MID,
    hsl: [hues.DESATURATED_RED, saturations.DESATURATED_RED, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_BROWN, simpleColors.SIMPLE_RED],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkRedBrown]: {
    name: complexColorNames.darkRedBrown,
    hueName: colorNames.RED,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.DARK,
    hsl: [hues.DESATURATED_RED, saturations.DESATURATED_RED, tints.DESAT_DARK],
    associations: [simpleColors.SIMPLE_BROWN, simpleColors.SIMPLE_RED],
    simpleOpts: { isSimpleColor: false },
  },
  // ORANGE-RED
  [complexColorNames.apricot]: {
    name: complexColorNames.apricot,
    hueName: colorNames.ORANGE_RED,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.LIGHT,
    hsl: [hues.ORANGE_RED, saturations.ORANGE_RED, tints.LIGHT],
    associations: [simpleColors.SIMPLE_ORANGE, simpleColors.SIMPLE_RED],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.orangeRed]: {
    name: complexColorNames.orangeRed,
    hueName: colorNames.ORANGE_RED,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.MID,
    hsl: [hues.ORANGE_RED, saturations.ORANGE_RED, tints.MID],
    associations: [simpleColors.SIMPLE_ORANGE, simpleColors.SIMPLE_RED],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkOrangeRed]: {
    name: complexColorNames.darkOrangeRed,
    hueName: colorNames.ORANGE_RED,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.DARK,
    hsl: [hues.ORANGE_RED, saturations.ORANGE_RED, tints.DARK],
    associations: [simpleColors.SIMPLE_ORANGE, simpleColors.SIMPLE_RED, simpleColors.SIMPLE_BROWN],
    simpleOpts: { isSimpleColor: false },
  },
  // CHOCOLATE BROWN
  [complexColorNames.lightChocolateBrown]: {
    name: complexColorNames.lightChocolateBrown,
    saturationType: saturationTypes.DESATURATED,
    hueName: colorNames.ORANGE_RED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.LIGHT,
    hsl: [hues.DESATURATED_ORANGE_RED, saturations.DESATURATED_ORANGE_RED, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_BROWN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.midChocolateBrown]: {
    name: complexColorNames.midChocolateBrown,
    saturationType: saturationTypes.DESATURATED,
    hueName: colorNames.ORANGE_RED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.MID,
    hsl: [hues.DESATURATED_ORANGE_RED, saturations.DESATURATED_ORANGE_RED, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_BROWN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.chocolateBrown]: {
    name: complexColorNames.chocolateBrown,
    hueName: colorNames.ORANGE_RED,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.DARK,
    hsl: [hues.DESATURATED_ORANGE_RED, saturations.DESATURATED_ORANGE_RED, tints.DESAT_DARK],
    associations: [simpleColors.SIMPLE_BROWN],
    simpleOpts: { isSimpleColor: false },
  },
  // ORANGE
  [complexColorNames.lightOrange]: {
    name: complexColorNames.lightOrange,
    hueName: colorNames.ORANGE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.LIGHT,
    hsl: [hues.ORANGE, saturations.ORANGE, tints.LIGHT],
    associations: [simpleColors.SIMPLE_ORANGE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.orange]: {
    name: complexColorNames.orange,
    hueName: colorNames.ORANGE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.MID,
    hsl: [hues.ORANGE, saturations.ORANGE, tints.MID],
    associations: [simpleColors.SIMPLE_ORANGE],
    simpleOpts: {
      id: simpleColors.SIMPLE_ORANGE,
      isSimpleColor: true,
      simpleOrder: 2,
    },
  },
  [complexColorNames.darkOrange]: {
    name: complexColorNames.darkOrange,
    hueName: colorNames.ORANGE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.DARK,
    hsl: [hues.ORANGE, saturations.ORANGE, tints.DARK],
    associations: [simpleColors.SIMPLE_ORANGE, simpleColors.SIMPLE_BROWN],
    simpleOpts: { isSimpleColor: false },
  },
  // BROWN (Desaturated orange)
  [complexColorNames.lightBrown]: {
    name: complexColorNames.lightBrown,
    hueName: colorNames.ORANGE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.LIGHT,
    hsl: [hues.DESATURATED_ORANGE, saturations.DESATURATED_ORANGE, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_BROWN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.brown]: {
    name: complexColorNames.brown,
    hueName: colorNames.ORANGE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.MID,
    hsl: [hues.DESATURATED_ORANGE, saturations.DESATURATED_ORANGE, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_BROWN],
    simpleOpts: {
      id: simpleColors.SIMPLE_BROWN,
      isSimpleColor: true,
      simpleOrder: 5,
    },
  },
  [complexColorNames.darkBrown]: {
    name: complexColorNames.darkBrown,
    hueName: colorNames.ORANGE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.DARK,
    hsl: [hues.DESATURATED_ORANGE, saturations.DESATURATED_ORANGE, tints.DESAT_DARK],
    associations: [simpleColors.SIMPLE_BROWN],
    simpleOpts: { isSimpleColor: false },
  },
  // GOLDEN YELLOW
  [complexColorNames.lightGoldenYellow]: {
    name: complexColorNames.lightGoldenYellow,
    hueName: colorNames.GOLDEN_YELLOW,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.LIGHT,
    hsl: [hues.GOLDEN_YELLOW, saturations.GOLDEN_YELLOW, tints.LIGHT],
    associations: [simpleColors.SIMPLE_YELLOW, simpleColors.SIMPLE_ORANGE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.goldenYellow]: {
    name: complexColorNames.goldenYellow,
    hueName: colorNames.GOLDEN_YELLOW,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.MID,
    hsl: [hues.GOLDEN_YELLOW, saturations.GOLDEN_YELLOW, tints.MID],
    associations: [simpleColors.SIMPLE_YELLOW, simpleColors.SIMPLE_ORANGE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkGoldenYellow]: {
    name: complexColorNames.darkGoldenYellow,
    hueName: colorNames.GOLDEN_YELLOW,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.DARK,
    hsl: [hues.GOLDEN_YELLOW, saturations.GOLDEN_YELLOW, tints.DARK],
    associations: [
      simpleColors.SIMPLE_YELLOW,
      simpleColors.SIMPLE_ORANGE,
      simpleColors.SIMPLE_BROWN,
    ],
    simpleOpts: { isSimpleColor: false },
  },
  // GOLDEN BROWN
  [complexColorNames.lightGoldenBrown]: {
    name: complexColorNames.lightGoldenBrown,
    hueName: colorNames.GOLDEN_YELLOW,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.LIGHT,
    hsl: [hues.DESATURATED_GOLDEN_YELLOW, saturations.DESATURATED_GOLDEN_YELLOW, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_BROWN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.goldenBrown]: {
    name: complexColorNames.goldenBrown,
    hueName: colorNames.GOLDEN_YELLOW,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.MID,
    hsl: [hues.DESATURATED_GOLDEN_YELLOW, saturations.DESATURATED_GOLDEN_YELLOW, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_BROWN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkGoldenBrown]: {
    name: complexColorNames.darkGoldenBrown,
    hueName: colorNames.GOLDEN_YELLOW,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.DARK,
    hsl: [hues.DESATURATED_GOLDEN_YELLOW, saturations.DESATURATED_GOLDEN_YELLOW, tints.DESAT_DARK],
    associations: [simpleColors.SIMPLE_BROWN],
    simpleOpts: { isSimpleColor: false },
  },
  // YELLOW
  [complexColorNames.lightYellow]: {
    name: complexColorNames.lightYellow,
    hueName: colorNames.YELLOW,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.LIGHT,
    hsl: [hues.YELLOW, saturations.YELLOW, tints.LIGHT],
    associations: [simpleColors.SIMPLE_YELLOW],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.yellow]: {
    name: complexColorNames.yellow,
    hueName: colorNames.YELLOW,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.MID,
    hsl: [hues.YELLOW, saturations.YELLOW, tints.MID],
    associations: [simpleColors.SIMPLE_YELLOW],
    simpleOpts: {
      id: simpleColors.SIMPLE_YELLOW,
      isSimpleColor: true,
      simpleOrder: 3,
    },
  },
  [complexColorNames.darkYellow]: {
    name: complexColorNames.darkYellow,
    saturationType: saturationTypes.SATURATED,
    hueName: colorNames.YELLOW,
    colorTemperature: colorTemperatures.WARM,
    degree: hues.YELLOW,
    saturation: saturations.YELLOW,
    tintName: tintNames.DARK,
    hsl: [hues.YELLOW, saturations.YELLOW, tints.DARK],
    associations: [simpleColors.SIMPLE_YELLOW, simpleColors.SIMPLE_BROWN],
    simpleOpts: { isSimpleColor: false },
  },
  // YELLOW-BROWN
  [complexColorNames.lightYellowBrown]: {
    name: complexColorNames.lightYellowBrown,
    hueName: colorNames.YELLOW,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.LIGHT,
    hsl: [hues.DESATURATED_YELLOW, saturations.DESATURATED_YELLOW, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_BROWN, simpleColors.SIMPLE_YELLOW],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.yellowBrown]: {
    name: complexColorNames.yellowBrown,
    hueName: colorNames.YELLOW,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.MID,
    hsl: [hues.DESATURATED_YELLOW, saturations.DESATURATED_YELLOW, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_BROWN, simpleColors.SIMPLE_YELLOW],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkYellowBrown]: {
    name: complexColorNames.darkYellowBrown,
    hueName: colorNames.YELLOW,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.WARM,
    tintName: tintNames.DARK,
    hsl: [hues.DESATURATED_YELLOW, saturations.DESATURATED_YELLOW, tints.DESAT_DARK],
    associations: [simpleColors.SIMPLE_BROWN, simpleColors.SIMPLE_YELLOW],
    simpleOpts: { isSimpleColor: false },
  },
  // YELLOW-GREEN
  [complexColorNames.lightYellowGreen]: {
    name: complexColorNames.lightYellowGreen,
    hueName: colorNames.YELLOW_GREEN,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.YELLOW_GREEN, saturations.YELLOW_GREEN, tints.DARKEST_LIGHT],
    associations: [simpleColors.SIMPLE_GREEN, simpleColors.SIMPLE_YELLOW],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.yellowGreen]: {
    name: complexColorNames.yellowGreen,
    hueName: colorNames.YELLOW_GREEN,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    hsl: [hues.YELLOW_GREEN, saturations.YELLOW_GREEN, tints.DARKEST_MID],
    associations: [simpleColors.SIMPLE_GREEN, simpleColors.SIMPLE_YELLOW],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkYellowGreen]: {
    name: complexColorNames.darkYellowGreen,
    hueName: colorNames.YELLOW_GREEN,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    degree: hues.YELLOW_GREEN,
    saturation: saturations.YELLOW_GREEN,
    tintName: tintNames.DARK,
    tintValue: tints.DARKER_DARK,
    hsl: [hues.YELLOW_GREEN, saturations.YELLOW_GREEN, tints.DARKEST_DARK],
    associations: [simpleColors.SIMPLE_GREEN, simpleColors.SIMPLE_YELLOW],
    simpleOpts: { isSimpleColor: false },
  },
  // OLIVE GREEN
  [complexColorNames.lightOliveGreen]: {
    name: complexColorNames.lightOliveGreen,
    hueName: colorNames.YELLOW_GREEN,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.DESATURATED_YELLOW_GREEN, saturations.DESATURATED_YELLOW_GREEN, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.oliveGreen]: {
    name: complexColorNames.oliveGreen,
    hueName: colorNames.YELLOW_GREEN,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    hsl: [hues.DESATURATED_YELLOW_GREEN, saturations.DESATURATED_YELLOW_GREEN, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkOliveGreen]: {
    name: complexColorNames.darkOliveGreen,
    hueName: colorNames.YELLOW_GREEN,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.DARK,
    hsl: [hues.DESATURATED_YELLOW_GREEN, saturations.DESATURATED_YELLOW_GREEN, tints.DESAT_DARK],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: { isSimpleColor: false },
  },
  // LIME GREEN
  [complexColorNames.lightLimeGreen]: {
    name: complexColorNames.lightLimeGreen,
    hueName: colorNames.GREEN,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.GREEN, saturations.GREEN, tints.LIGHT],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.limeGreen]: {
    name: complexColorNames.limeGreen,
    hueName: colorNames.GREEN,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    hsl: [hues.GREEN, saturations.GREEN, tints.MID],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkLimeGreen]: {
    name: complexColorNames.darkLimeGreen,
    hueName: colorNames.GREEN,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.DARK,
    hsl: [hues.GREEN, saturations.GREEN, tints.DARKER_DARK],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: { isSimpleColor: false },
  },
  // DESATURATED LIME GREEN
  [complexColorNames.lightForestGreen]: {
    name: complexColorNames.lightForestGreen,
    hueName: colorNames.GREEN,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.DESATURATED_GREEN, saturations.DESATURATED_GREEN, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.forestGreen]: {
    name: complexColorNames.forestGreen,
    hueName: colorNames.GREEN,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    hsl: [hues.DESATURATED_GREEN, saturations.DESATURATED_GREEN, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkForestGreen]: {
    name: complexColorNames.darkForestGreen,
    hueName: colorNames.GREEN,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.DARK,
    hsl: [hues.DESATURATED_GREEN, saturations.DESATURATED_GREEN, tints.DESAT_DARK],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: { isSimpleColor: false },
  },
  // SPRING GREEN
  [complexColorNames.lightSpringGreen]: {
    name: complexColorNames.lightSpringGreen,
    hueName: colorNames.SPRING_GREEN,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.SPRING_GREEN, saturations.SPRING_GREEN, tints.LIGHT],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.springGreen]: {
    name: complexColorNames.springGreen,
    saturationType: saturationTypes.SATURATED,
    hueName: colorNames.SPRING_GREEN,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    hsl: [hues.SPRING_GREEN, saturations.SPRING_GREEN, tints.MID],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.green]: {
    name: complexColorNames.green,
    saturationType: saturationTypes.SATURATED,
    hueName: colorNames.SPRING_GREEN,
    colorTemperature: colorTemperatures.COOL,
    degree: hues.SPRING_GREEN,
    saturation: saturations.SPRING_GREEN,
    tintName: tintNames.DARK,
    hsl: [hues.SPRING_GREEN, saturations.SPRING_GREEN, tints.DARK],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: {
      id: simpleColors.SIMPLE_GREEN,
      isSimpleColor: true,
      simpleOrder: 4,
    },
  },
  // DESATURATED SPRING GREEN
  [complexColorNames.lightSeaGreen]: {
    name: complexColorNames.lightSeaGreen,
    saturationType: saturationTypes.DESATURATED,
    hueName: colorNames.SPRING_GREEN,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.DESATURATED_SPRING_GREEN, saturations.DESATURATED_SPRING_GREEN, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.seaGreen]: {
    name: complexColorNames.seaGreen,
    hueName: colorNames.SPRING_GREEN,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    hsl: [hues.DESATURATED_SPRING_GREEN, saturations.DESATURATED_SPRING_GREEN, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkSeaGreen]: {
    name: complexColorNames.darkSeaGreen,
    hueName: colorNames.SPRING_GREEN,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.DARK,
    hsl: [hues.DESATURATED_SPRING_GREEN, saturations.DESATURATED_SPRING_GREEN, tints.DESAT_DARK],
    associations: [simpleColors.SIMPLE_GREEN],
    simpleOpts: { isSimpleColor: false },
  },
  // TURQUOISE
  [complexColorNames.lightTurquoise]: {
    name: complexColorNames.lightTurquoise,
    saturationType: saturationTypes.SATURATED,
    hueName: colorNames.TURQUOISE,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.TURQUOISE, saturations.TURQUOISE, tints.DARKEST_LIGHT],
    associations: [simpleColors.SIMPLE_GREEN, simpleColors.SIMPLE_BLUE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.turquoise]: {
    name: complexColorNames.turquoise,
    saturationType: saturationTypes.SATURATED,
    hueName: colorNames.TURQUOISE,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    tintValue: tints.DARKER_MID,
    hsl: [hues.TURQUOISE, saturations.TURQUOISE, tints.DARKEST_MID],
    associations: [simpleColors.SIMPLE_GREEN, simpleColors.SIMPLE_BLUE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.teal]: {
    name: complexColorNames.teal,
    hueName: colorNames.TURQUOISE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.DARK,
    hsl: [hues.TURQUOISE, saturations.TURQUOISE, tints.DARKEST_DARK],
    associations: [simpleColors.SIMPLE_GREEN, simpleColors.SIMPLE_BLUE],
    simpleOpts: { isSimpleColor: false },
  },
  // DESATURATED TURQUOISE
  [complexColorNames.lightBlueGreen]: {
    name: complexColorNames.lightBlueGreen,
    hueName: colorNames.TURQUOISE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.DESATURATED_TURQUOISE, saturations.DESATURATED_TURQUOISE, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_GREEN, simpleColors.SIMPLE_BLUE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.blueGreen]: {
    name: complexColorNames.blueGreen,
    hueName: colorNames.TURQUOISE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    hsl: [hues.DESATURATED_TURQUOISE, saturations.DESATURATED_TURQUOISE, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_GREEN, simpleColors.SIMPLE_BLUE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkBlueGreen]: {
    name: complexColorNames.darkBlueGreen,
    hueName: colorNames.TURQUOISE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.DARK,
    hsl: [hues.DESATURATED_TURQUOISE, saturations.DESATURATED_TURQUOISE, tints.DESAT_DARK],
    associations: [simpleColors.SIMPLE_GREEN, simpleColors.SIMPLE_BLUE],
    simpleOpts: { isSimpleColor: false },
  },
  // SKY BLUE / AZURE
  [complexColorNames.lightBlue]: {
    name: complexColorNames.lightBlue,
    hueName: colorNames.SKY_BLUE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.SKY_BLUE, saturations.SKY_BLUE, tints.LIGHT],
    associations: [simpleColors.SIMPLE_BLUE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.blue]: {
    name: complexColorNames.blue,
    hueName: colorNames.SKY_BLUE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    associations: [simpleColors.SIMPLE_BLUE],
    hsl: [hues.SKY_BLUE, saturations.SKY_BLUE, tints.MID],
    simpleOpts: {
      id: simpleColors.SIMPLE_BLUE,
      isSimpleColor: true,
      simpleOrder: 6,
    },
  },
  [complexColorNames.prussianBlue]: {
    name: complexColorNames.prussianBlue,
    hueName: colorNames.SKY_BLUE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.DARK,
    hsl: [hues.SKY_BLUE, saturations.SKY_BLUE, tints.DARKER_DARK],
    associations: [simpleColors.SIMPLE_BLUE],
    simpleOpts: { isSimpleColor: false },
  },
  // DESATURATED SKY BLUE
  [complexColorNames.lightBlueGray]: {
    name: complexColorNames.lightBlueGray,
    hueName: colorNames.SKY_BLUE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.DESATURATED_SKY_BLUE, saturations.DESATURATED_SKY_BLUE, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_BLUE, simpleColors.SIMPLE_GRAY],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.blueGray]: {
    name: complexColorNames.blueGray,
    hueName: colorNames.SKY_BLUE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    hsl: [hues.DESATURATED_SKY_BLUE, saturations.DESATURATED_SKY_BLUE, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_BLUE, simpleColors.SIMPLE_GRAY],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkBlueGray]: {
    name: complexColorNames.darkBlueGray,
    hueName: colorNames.SKY_BLUE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.DARK,
    hsl: [hues.DESATURATED_SKY_BLUE, saturations.DESATURATED_SKY_BLUE, tints.DESAT_DARK],
    associations: [simpleColors.SIMPLE_BLUE, simpleColors.SIMPLE_GRAY],
    simpleOpts: { isSimpleColor: false },
  },
  // ROYAL BLUE
  [complexColorNames.cornflowerBlue]: {
    name: complexColorNames.cornflowerBlue,
    hueName: colorNames.BLUE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.BLUE, saturations.BLUE, tints.LIGHT],
    associations: [simpleColors.SIMPLE_BLUE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.royalBlue]: {
    name: complexColorNames.royalBlue,
    hueName: colorNames.BLUE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    degree: hues.BLUE,
    saturation: saturations.BLUE,
    tintName: tintNames.MID,
    hsl: [hues.BLUE, saturations.BLUE, tints.MID],
    associations: [simpleColors.SIMPLE_BLUE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkRoyalBlue]: {
    name: complexColorNames.darkRoyalBlue,
    hueName: colorNames.BLUE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.DARK,
    hsl: [hues.BLUE, saturations.BLUE, tints.DARK],
    associations: [simpleColors.SIMPLE_BLUE],
    simpleOpts: { isSimpleColor: false },
  },
  // DESATURATED ROYAL BLUE
  [complexColorNames.lightSlateBlue]: {
    name: complexColorNames.lightSlateBlue,
    hueName: colorNames.BLUE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.DESATURATED_BLUE, saturations.DESATURATED_BLUE, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_BLUE, simpleColors.SIMPLE_GRAY],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.slateBlue]: {
    name: complexColorNames.slateBlue,
    hueName: colorNames.BLUE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    tintValue: tints.DARKER_MID,
    hsl: [hues.DESATURATED_BLUE, saturations.DESATURATED_BLUE, tints.DARKER_MID],
    associations: [simpleColors.SIMPLE_BLUE, simpleColors.SIMPLE_GRAY],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkSlateBlue]: {
    name: complexColorNames.darkSlateBlue,
    hueName: colorNames.BLUE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.DARK,
    tintValue: tints.DARKEST_DARK,
    hsl: [hues.DESATURATED_BLUE, saturations.DESATURATED_BLUE, tints.DARKEST_DARK],
    associations: [simpleColors.SIMPLE_BLUE, simpleColors.SIMPLE_GRAY, simpleColors.SIMPLE_BLACK],
    simpleOpts: { isSimpleColor: false },
  },
  // BLUE_PURPLE
  [complexColorNames.lightPurpleBlue]: {
    name: complexColorNames.lightPurpleBlue,
    hueName: colorNames.BLUE_PURPLE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.BLUE_PURPLE, saturations.BLUE_PURPLE, tints.LIGHT],
    associations: [simpleColors.SIMPLE_PURPLE, simpleColors.SIMPLE_BLUE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.purpleBlue]: {
    name: complexColorNames.purpleBlue,
    hueName: colorNames.BLUE_PURPLE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    hsl: [hues.BLUE_PURPLE, saturations.BLUE_PURPLE, tints.MID],
    associations: [simpleColors.SIMPLE_PURPLE, simpleColors.SIMPLE_BLUE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkPurpleBlue]: {
    name: complexColorNames.darkPurpleBlue,
    hueName: colorNames.BLUE_PURPLE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.DARK,
    hsl: [hues.BLUE_PURPLE, saturations.BLUE_PURPLE, tints.DARK],
    associations: [simpleColors.SIMPLE_PURPLE, simpleColors.SIMPLE_BLUE],
    simpleOpts: { isSimpleColor: false },
  },
  // DESATURED PURPLE BLUE
  [complexColorNames.lightDuskyBluePurple]: {
    name: complexColorNames.lightDuskyBluePurple,
    hueName: colorNames.BLUE_PURPLE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    degree: hues.DESATURATED_BLUE_PURPLE,
    saturation: saturations.DESATURATED_BLUE_PURPLE,
    tintName: tintNames.LIGHT,
    hsl: [hues.DESATURATED_BLUE_PURPLE, saturations.DESATURATED_BLUE_PURPLE, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_PURPLE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.duskyBluePurple]: {
    name: complexColorNames.duskyBluePurple,
    hueName: colorNames.BLUE_PURPLE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    hsl: [hues.DESATURATED_BLUE_PURPLE, saturations.DESATURATED_BLUE_PURPLE, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_PURPLE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkDuskyBluePurple]: {
    name: complexColorNames.darkDuskyBluePurple,
    hueName: colorNames.BLUE_PURPLE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    degree: hues.DESATURATED_BLUE_PURPLE,
    saturation: saturations.DESATURATED_BLUE_PURPLE,
    tintName: tintNames.DARK,
    hsl: [hues.DESATURATED_BLUE_PURPLE, saturations.DESATURATED_BLUE_PURPLE, tints.DESAT_DARK],
    associations: [simpleColors.SIMPLE_PURPLE],
    simpleOpts: { isSimpleColor: false },
  },
  // PURPLE
  [complexColorNames.lightPurple]: {
    name: complexColorNames.lightPurple,
    hueName: colorNames.PURPLE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.PURPLE, saturations.PURPLE, tints.LIGHT],
    associations: [simpleColors.SIMPLE_PURPLE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.purple]: {
    name: complexColorNames.purple,
    hueName: colorNames.PURPLE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    associations: [simpleColors.SIMPLE_PURPLE],
    hsl: [hues.PURPLE, saturations.PURPLE, tints.MID],
    simpleOpts: {
      id: simpleColors.SIMPLE_PURPLE,
      isSimpleColor: true,
      simpleOrder: 7,
    },
  },
  [complexColorNames.darkPurple]: {
    name: complexColorNames.darkPurple,
    hueName: colorNames.PURPLE,
    saturationType: saturationTypes.SATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.DARK,
    hsl: [hues.PURPLE, saturations.PURPLE, tints.DARK],
    associations: [simpleColors.SIMPLE_PURPLE],
    simpleOpts: { isSimpleColor: false },
  },
  // DESAUTRATED PURPLE
  [complexColorNames.lightDuskyPurple]: {
    name: complexColorNames.lightDuskyPurple,
    hueName: colorNames.PURPLE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.LIGHT,
    hsl: [hues.DESATURATED_PURPLE, saturations.DESATURATED_PURPLE, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_PURPLE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.duskyPurple]: {
    name: complexColorNames.duskyPurple,
    saturationType: saturationTypes.DESATURATED,
    hueName: colorNames.PURPLE,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.MID,
    hsl: [hues.DESATURATED_PURPLE, saturations.DESATURATED_PURPLE, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_PURPLE],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.darkDuskyPurple]: {
    name: complexColorNames.darkDuskyPurple,
    hueName: colorNames.PURPLE,
    saturationType: saturationTypes.DESATURATED,
    colorTemperature: colorTemperatures.COOL,
    tintName: tintNames.DARK,
    hsl: [hues.DESATURATED_PURPLE, saturations.DESATURATED_PURPLE, tints.DESAT_DARK],
    associations: [simpleColors.SIMPLE_PURPLE],
    simpleOpts: { isSimpleColor: false },
  },
  // BLACK
  [complexColorNames.black]: {
    name: complexColorNames.black,
    hueName: colorNames.BLACK,
    saturationType: saturationTypes.CUSTOM,
    colorTemperature: colorTemperatures.NEUTRAL,
    tintName: tintNames.CUSTOM,
    hsl: [hues.BLACK, saturations.BLACK, tints.BLACK],
    associations: [simpleColors.SIMPLE_BLACK],
    simpleOpts: {
      id: simpleColors.SIMPLE_BLACK,
      isSimpleColor: true,
      simpleOrder: 8,
    },
  },
  // GRAY
  [complexColorNames.lightGray]: {
    name: complexColorNames.lightGray,
    hueName: colorNames.GRAY,
    saturationType: saturationTypes.CUSTOM,
    colorTemperature: colorTemperatures.NEUTRAL,
    tintName: tintNames.LIGHT,
    hsl: [hues.GRAY, saturations.GRAY, tints.DESAT_LIGHT],
    associations: [simpleColors.SIMPLE_GRAY],
    simpleOpts: { isSimpleColor: false },
  },
  [complexColorNames.gray]: {
    name: complexColorNames.gray,
    hueName: colorNames.GRAY,
    saturationType: saturationTypes.CUSTOM,
    colorTemperature: colorTemperatures.NEUTRAL,
    tintName: tintNames.MID,
    hsl: [hues.GRAY, saturations.GRAY, tints.DESAT_MID],
    associations: [simpleColors.SIMPLE_GRAY],
    simpleOpts: {
      id: simpleColors.SIMPLE_GRAY,
      isSimpleColor: true,
      simpleOrder: 9,
    },
  },
  [complexColorNames.darkGray]: {
    name: complexColorNames.darkGray,
    hueName: colorNames.GRAY,
    saturationType: saturationTypes.CUSTOM,
    colorTemperature: colorTemperatures.NEUTRAL,
    tintName: tintNames.DARK,
    hsl: [hues.GRAY, saturations.GRAY, tints.DARKEST_DARK],
    associations: [simpleColors.SIMPLE_GRAY, simpleColors.SIMPLE_BLACK],
    simpleOpts: { isSimpleColor: false },
  },
  // WHITE
  [complexColorNames.white]: {
    name: complexColorNames.white,
    hueName: colorNames.WHITE,
    saturationType: saturationTypes.CUSTOM,
    colorTemperature: colorTemperatures.NEUTRAL,
    tintName: tintNames.CUSTOM,
    hsl: [hues.WHITE, saturations.WHITE, tints.WHITE],
    associations: [simpleColors.SIMPLE_WHITE],
    simpleOpts: {
      id: simpleColors.SIMPLE_WHITE,
      isSimpleColor: true,
      simpleOrder: 10,
    },
  },
  // CREAM
  [complexColorNames.cream]: {
    name: complexColorNames.cream,
    hueName: colorNames.CREAM,
    saturationType: saturationTypes.CUSTOM,
    colorTemperature: colorTemperatures.NEUTRAL,
    tintName: tintNames.CUSTOM,
    hsl: [hues.CREAM, saturations.CREAM, tints.CREAM],
    associations: [simpleColors.SIMPLE_WHITE],
    simpleOpts: { isSimpleColor: false },
  },
  // GOLD
  [complexColorNames.gold]: {
    name: complexColorNames.gold,
    hueName: colorNames.GOLD,
    saturationType: saturationTypes.CUSTOM,
    colorTemperature: colorTemperatures.METALLIC,
    tintName: tintNames.CUSTOM,
    hsl: [hues.GOLD, saturations.GOLD, tints.GOLD],
    associations: [simpleColors.SIMPLE_YELLOW],
    simpleOpts: { isSimpleColor: false },
  },
  // SILVER
  [complexColorNames.silver]: {
    name: complexColorNames.silver,
    hueName: colorNames.SILVER,
    saturationType: saturationTypes.CUSTOM,
    colorTemperature: colorTemperatures.METALLIC,
    tintName: tintNames.CUSTOM,
    hsl: [hues.SILVER, saturations.SILVER, tints.SILVER],
    associations: [simpleColors.SIMPLE_GRAY],
    simpleOpts: { isSimpleColor: false },
  },
  // BRONZE
  [complexColorNames.bronze]: {
    name: complexColorNames.bronze,
    hueName: colorNames.BRONZE,
    saturationType: saturationTypes.CUSTOM,
    colorTemperature: colorTemperatures.METALLIC,
    tintName: tintNames.CUSTOM,
    hsl: [hues.BRONZE, saturations.BRONZE, tints.BRONZE],
    associations: [simpleColors.SIMPLE_BROWN],
    simpleOpts: { isSimpleColor: false },
  },
};

export const huesList = Object.values(hues);
